project:
  type: website

website:
  title: "Hawai ªi Wildlife Strandings Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: monk-seals.qmd
        text: Monk Seals
      - href: sea-turtles.qmd
        text: Sea Turtles
      - href: data-cleaning.qmd
        text: Data Cleaning

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
