project:
  type: website
  output-dir: docs

website:
  # title: "Monk Seal Inicident Dashboard"
  navbar:
    left:
      - href: index.qmd
    right:
      - icon: github
        href: "https://brandonkoskie.github.io/"
        text: "My Website"

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true

editor: visual

